# -*- coding: utf-8 -*-
from odoo import api, fields, models, _
from odoo.exceptions import UserError
import base64
import logging

_logger = logging.getLogger(__name__)


class FleetBookingInvoiceDocument(models.Model):
    _name = 'fleet.booking.invoice.document'
    _description = 'Fleet Booking Invoice Document Archive'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'generation_date desc, id desc'
    _rec_name = 'document_name'

    # Basic Information
    document_name = fields.Char(
        string='Document Name',
        required=True,
        readonly=True,
        copy=False,
        tracking=True
    )

    booking_id = fields.Many2one(
        'fleet.booking',
        string='Booking',
        required=True,
        ondelete='cascade',
        index=True,
        tracking=True
    )

    booking_name = fields.Char(
        related='booking_id.name',
        string='Booking Reference',
        store=True,
        readonly=True
    )

    # Document Storage
    pdf_file = fields.Binary(
        string='PDF File',
        required=True,
        help='The generated invoice PDF file'
    )
    
    pdf_file_attachment_id = fields.Many2one(
        'ir.attachment',
        string='PDF Attachment',
        compute='_compute_pdf_file_attachment_id',
        store=False,
        help='Link to the attachment record for web access'
    )

    pdf_filename = fields.Char(
        string='Filename',
        required=True,
        readonly=True
    )

    file_size = fields.Integer(
        string='File Size (bytes)',
        readonly=True,
        help='Size of the PDF file in bytes'
    )

    file_size_formatted = fields.Char(
        string='File Size',
        compute='_compute_file_size_formatted',
        store=True
    )

    # Stage Information
    booking_state = fields.Selection([
        ('enquiry', 'Enquiry'),
        ('quotation', 'Quotation'),
        ('followup', 'Follow Up'),
        ('confirmed', 'Confirmed'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
        ('feedback', 'Feedback'),
    ], string='Booking Stage', required=True, readonly=True, tracking=True,
        help='The booking stage when this invoice was generated')

    # Generation Information
    generation_date = fields.Datetime(
        string='Generated On',
        required=True,
        readonly=True,
        default=fields.Datetime.now,
        tracking=True
    )

    generated_by = fields.Many2one(
        'res.users',
        string='Generated By',
        required=True,
        readonly=True,
        default=lambda self: self.env.user,
        tracking=True
    )

    # Customer Information (for quick reference)
    customer_id = fields.Many2one(
        related='booking_id.customer_id',
        string='Customer',
        store=True,
        readonly=True
    )

    company_name = fields.Char(
        related='booking_id.company_name',
        string='Company Name',
        store=True,
        readonly=True
    )

    # Financial Information (for quick reference)
    total_amount = fields.Monetary(
        related='booking_id.total_price',
        string='Total Amount',
        store=True,
        readonly=True
    )

    currency_id = fields.Many2one(
        related='booking_id.currency_id',
        string='Currency',
        store=True,
        readonly=True
    )

    # Additional Information
    notes = fields.Text(
        string='Notes',
        help='Additional notes about this document generation'
    )

    active = fields.Boolean(
        string='Active',
        default=True,
        help='Uncheck to archive this document'
    )

    company_id = fields.Many2one(
        'res.company',
        string='Company',
        required=True,
        readonly=True,
        default=lambda self: self.env.company
    )

    # Computed Fields
    @api.depends('file_size')
    def _compute_file_size_formatted(self):
        """Format file size in human-readable format"""
        for record in self:
            if record.file_size:
                size = record.file_size
                if size < 1024:
                    record.file_size_formatted = "{} B".format(size)
                elif size < 1024 * 1024:
                    record.file_size_formatted = "{:.2f} KB".format(size / 1024)
                else:
                    record.file_size_formatted = "{:.2f} MB".format(size / (1024 * 1024))
            else:
                record.file_size_formatted = "0 B"
    
    def _compute_pdf_file_attachment_id(self):
        """Get the ir.attachment record for the PDF file"""
        for record in self:
            attachment = self.env['ir.attachment'].search([
                ('res_model', '=', self._name),
                ('res_id', '=', record.id),
                ('res_field', '=', 'pdf_file')
            ], limit=1)
            record.pdf_file_attachment_id = attachment

    def name_get(self):
        """Custom name display"""
        result = []
        for record in self:
            state_labels = {
                'enquiry': 'Enquiry',
                'quotation': 'Quotation',
                'followup': 'Follow Up',
                'confirmed': 'Confirmed',
                'completed': 'Completed',
                'cancelled': 'Cancelled',
                'feedback': 'Feedback',
            }
            state_label = state_labels.get(record.booking_state, record.booking_state)
            name = "{} - {} - {}".format(
                record.booking_name,
                state_label,
                record.generation_date.strftime('%Y-%m-%d %H:%M')
            )
            result.append((record.id, name))
        return result
    
    def _ensure_attachment_name(self):
        """Ensure the attachment has the proper filename for downloads"""
        self.ensure_one()
        
        # Find the attachment for this record's pdf_file
        attachment = self.env['ir.attachment'].search([
            ('res_model', '=', self._name),
            ('res_id', '=', self.id),
            ('res_field', '=', 'pdf_file')
        ], limit=1)
        
        if attachment and attachment.name != self.pdf_filename:
            attachment.sudo().write({
                'name': self.pdf_filename,
                'mimetype': 'application/pdf',
            })

    @api.model
    def generate_invoice_pdf(self, booking_id, booking_state):
        """
        Generate and save invoice PDF for a booking at a specific state

        Args:
            booking_id: ID of the fleet.booking record
            booking_state: Current state of the booking

        Returns:
            fleet.booking.invoice.document record
        """
        try:
            # Get booking record
            booking = self.env['fleet.booking'].browse(booking_id)
            if not booking.exists():
                raise UserError("Booking record not found.")

            # Check if document already exists for this state
            existing_doc = self.search([
                ('booking_id', '=', booking_id),
                ('booking_state', '=', booking_state)
            ], limit=1)

            # Get the report - FIXED: Proper way to get report in Odoo 17
            try:
                report = self.env['ir.actions.report']._get_report_from_name(
                    'fleet_booking.report_fleet_booking_invoice'
                )
            except Exception:
                # Fallback method if above doesn't work
                report = self.env.ref(
                    'fleet_booking.action_report_fleet_booking_invoice',
                    raise_if_not_found=False
                )

            if not report:
                raise UserError(
                    "Invoice report not found. "
                    "Please check your fleet_booking module configuration."
                )

            # FIXED: Proper way to render PDF in Odoo 17
            # Method 1: Using report directly
            try:
                pdf_content, content_type = report._render_qweb_pdf(
                    report.id,
                    res_ids=[booking.id]
                )
            except Exception as e1:
                _logger.warning("Method 1 failed, trying method 2: {}".format(str(e1)))
                # Method 2: Alternative approach
                try:
                    pdf_content, content_type = report.sudo()._render_qweb_pdf(
                        res_ids=booking.id
                    )
                except Exception as e2:
                    _logger.warning("Method 2 failed, trying method 3: {}".format(str(e2)))
                    # Method 3: Using report action
                    pdf_content, content_type = self.env['ir.actions.report'].sudo()._render_qweb_pdf(
                        'fleet_booking.action_report_fleet_booking_invoice',
                        res_ids=[booking.id]
                    )

            if not pdf_content:
                raise UserError("Failed to generate PDF content.")

            # Get state label safely
            state_labels = {
                'enquiry': 'Enquiry',
                'quotation': 'Quotation',
                'followup': 'Follow Up',
                'confirmed': 'Confirmed',
                'completed': 'Completed',
                'cancelled': 'Cancelled',
                'feedback': 'Feedback',
            }
            state_label = state_labels.get(booking_state, booking_state.capitalize())

            # Create safe filename (remove special characters)
            safe_booking_name = booking.name.replace('/', '_').replace('\\', '_')
            safe_state_label = state_label.replace(' ', '_')
            timestamp = fields.Datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = "Invoice_{}_{}_{}{}".format(
                safe_booking_name,
                safe_state_label,
                timestamp,
                '.pdf'
            )

            # Document name
            document_name = "{} - {} Invoice".format(booking.name, state_label)

            # Prepare values
            vals = {
                'document_name': document_name,
                'booking_id': booking_id,
                'booking_state': booking_state,
                'pdf_file': base64.b64encode(pdf_content),
                'pdf_filename': filename,
                'file_size': len(pdf_content),
                'generation_date': fields.Datetime.now(),
                'generated_by': self.env.user.id,
                'company_id': booking.company_id.id,
            }

            # Update existing or create new
            if existing_doc:
                existing_doc.write(vals)
                document = existing_doc
                action_msg = "updated"
            else:
                document = self.create(vals)
                action_msg = "generated"
            
            # CRITICAL: Manually create/update ir.attachment with proper settings
            # This ensures the file is accessible via /web/content
            attachment_vals = {
                'name': filename,
                'datas': base64.b64encode(pdf_content),
                'res_model': self._name,
                'res_id': document.id,
                'res_field': 'pdf_file',
                'type': 'binary',
                'mimetype': 'application/pdf',
                'public': True,  # Make it publicly accessible
            }
            
            # Check if attachment already exists
            existing_attachment = self.env['ir.attachment'].sudo().search([
                ('res_model', '=', self._name),
                ('res_id', '=', document.id),
                ('res_field', '=', 'pdf_file')
            ], limit=1)
            
            if existing_attachment:
                existing_attachment.sudo().write(attachment_vals)
            else:
                self.env['ir.attachment'].sudo().create(attachment_vals)

            # Log in booking chatter
            message_body = "Invoice PDF automatically {} for stage <b>{}</b>.<br/>File: <b>{}</b> ({})".format(
                action_msg, state_label, filename, document.file_size_formatted
            )
            booking.message_post(body=message_body, message_type='notification')

            _logger.info("Invoice PDF {} for booking {} at stage {}".format(
                action_msg, booking.name, booking_state
            ))

            return document

        except UserError as ue:
            _logger.error("UserError generating invoice PDF for booking {}: {}".format(
                booking_id, str(ue)
            ))
            raise
        except Exception as e:
            error_msg = "Error generating invoice PDF for booking {}: {}".format(
                booking_id, str(e)
            )
            _logger.error(error_msg)
            import traceback
            _logger.error(traceback.format_exc())
            raise UserError("Failed to generate invoice PDF: {}".format(str(e)))

    def action_download_pdf(self):
        """Download the PDF file"""
        self.ensure_one()

        if not self.pdf_file:
            raise UserError("No PDF file available to download.")

        # Get or create the attachment
        attachment = self.env['ir.attachment'].search([
            ('res_model', '=', self._name),
            ('res_id', '=', self.id),
            ('res_field', '=', 'pdf_file')
        ], limit=1)

        if attachment:
            # Use attachment ID for more reliable access
            return {
                'type': 'ir.actions.act_url',
                'url': '/web/content/{}?download=true'.format(attachment.id),
                'target': 'new',
            }
        else:
            # Fallback to field-based URL
            return {
                'type': 'ir.actions.act_url',
                'url': '/web/content?model={}&id={}&field=pdf_file&filename={}&download=true'.format(
                    self._name, self.id, self.pdf_filename
                ),
                'target': 'new',
            }

    def action_view_pdf(self):
        """View the PDF file in browser"""
        self.ensure_one()

        if not self.pdf_file:
            raise UserError("No PDF file available to view.")

        # Get or create the attachment
        attachment = self.env['ir.attachment'].search([
            ('res_model', '=', self._name),
            ('res_id', '=', self.id),
            ('res_field', '=', 'pdf_file')
        ], limit=1)

        if attachment:
            # Use attachment ID for more reliable access
            return {
                'type': 'ir.actions.act_url',
                'url': '/web/content/{}'.format(attachment.id),
                'target': 'new',
            }
        else:
            # Fallback to field-based URL
            return {
                'type': 'ir.actions.act_url',
                'url': '/web/content?model={}&id={}&field=pdf_file&filename={}'.format(
                    self._name, self.id, self.pdf_filename
                ),
                'target': 'new',
            }

    def action_regenerate_pdf(self):
        """Manually regenerate PDF for current stage"""
        self.ensure_one()

        try:
            # Regenerate PDF
            self.generate_invoice_pdf(self.booking_id.id, self.booking_state)

            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': 'Success',
                    'message': 'Invoice PDF has been regenerated successfully.',
                    'type': 'success',
                }
            }
        except Exception as e:
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': 'Error',
                    'message': str(e),
                    'type': 'danger',
                }
            }

    def action_open_booking(self):
        """Open the related booking record"""
        self.ensure_one()

        return {
            'type': 'ir.actions.act_window',
            'name': 'Booking',
            'res_model': 'fleet.booking',
            'res_id': self.booking_id.id,
            'view_mode': 'form',
            'target': 'current',
        }